FROM ubuntu:xenial-20181113

ENV DEBIAN_FRONTEND=noninteractive

#RUN set -e -x ;\
#    apt-get -y update ;\
#    apt-get -y upgrade ;\
#    apt-get -y install \
#        build-essential autoconf cmake clang bison wget flex gperf \
#        libreadline-dev gawk tcl-dev libffi-dev graphviz xdot python3-dev \
#        libboost-all-dev qt5-default git libftdi-dev pkg-config

RUN set -e -x ;\
    apt-get -y update ;\
    apt-get -y upgrade ;\
    apt-get -y install \
        build-essential autoconf cmake clang bison wget flex gperf \
        libreadline-dev gawk tcl-dev libffi-dev graphviz xdot python3-dev \
        libboost-all-dev git libftdi-dev pkg-config

# get most recent release version of Yosys
RUN set -e -x ;\
    mkdir -p /usr/local/src ;\
    cd /usr/local/src ;\
    git clone --recursive https://github.com/YosysHQ/yosys.git ;\
    cd yosys ;\
    latestTag=$(git describe --tags `git rev-list --tags --max-count=1`) ;\
    git checkout $latestTag ;\
    make -j $(nproc) ;\
    make install ;\
    rm -rf /usr/local/src/yosys

