task:
  name: sanity-test-ubuntu1604
  container:
    cpu: 1
    memory: 16
    dockerfile: .cirrus/Dockerfile.ubuntu16.04
  env:
    GITHUB_TOKEN: ENCRYPTED[c86a89228a6bd63329c6e28f2228d48e79a47a9fa0481d3e15f0f30b0e74fa26b5748afd1e44523e90450d53911e67f4]
  permission_script: mkdir reports && chmod +x ./scripts/database_make.py && chmod +x ./scripts/database_html.sh && chmod +x .cirrus/upload.sh
  sanity_script: ./scripts/database_make.py yosys-sanity ./verilog/ && ./scripts/database_html.sh && cp ./database/index.html ./reports/benchmarks_sanity.html
  push_script:  .cirrus/upload.sh

task:
  name: small-test-ubuntu1604
  container:
    cpu: 1
    memory: 16
    dockerfile: .cirrus/Dockerfile.ubuntu16.04
  env:
    GITHUB_TOKEN: ENCRYPTED[c86a89228a6bd63329c6e28f2228d48e79a47a9fa0481d3e15f0f30b0e74fa26b5748afd1e44523e90450d53911e67f4]
  permission_script: mkdir reports && chmod +x ./scripts/database_make.py && chmod +x ./scripts/database_html.sh && chmod +x .cirrus/upload.sh
  small_script: ./scripts/database_make.py yosys-ice40-lutcount ./verilog/benchmarks_small/ && ./scripts/database_html.sh && cp ./database/index.html ./reports/benchmarks_small.html
  push_script:  .cirrus/upload.sh

task:
  name: large-test-ubuntu1604
  container:
    cpu: 1
    memory: 16
    dockerfile: .cirrus/Dockerfile.ubuntu16.04
  env:
    GITHUB_TOKEN: ENCRYPTED[c86a89228a6bd63329c6e28f2228d48e79a47a9fa0481d3e15f0f30b0e74fa26b5748afd1e44523e90450d53911e67f4]
    EXTRA_FLAGS: -noflatten
  permission_script: mkdir reports && chmod +x ./scripts/database_make.py && chmod +x ./scripts/database_html.sh && chmod +x .cirrus/upload.sh
  large_script: ./scripts/database_make.py yosys-ice40-lutcount ./verilog/benchmarks_large/ && ./scripts/database_html.sh && cp ./database/index.html ./reports/benchmarks_large.html
  push_script:  .cirrus/upload.sh

