task:
  name: build-test-ubuntu1604
  container:
    cpu: 4
    memory: 16
    dockerfile: .cirrus/Dockerfile.ubuntu16.04
    
  permission_script: mkdir reports && chmod +x ./script/database_py.sh && chmod +x ./script/database_html.sh
  small_script: ./script/database_py.sh ./scripts/database_make.py yosys-ice40-lutcount ./verilog/benchmarks_small/ && ./script/database_html.sh && cp ./database/index.html ./reports/benchmarks_small.html
  large_script: ./script/database_py.sh ./scripts/database_make.py yosys-ice40-lutcount ./verilog/benchmarks_small/ && ./script/database_html.sh && cp ./database/index.html ./reports/benchmarks_large.html
  reports_artifact: 
    store: always
    path:  reports
