task:
  name: build-test-ubuntu1604
  container:
    cpu: 4
    memory: 16
    dockerfile: .cirrus/Dockerfile.ubuntu16.04
  env:
    GITHUB_TOKEN: ENCRYPTED[c86a89228a6bd63329c6e28f2228d48e79a47a9fa0481d3e15f0f30b0e74fa26b5748afd1e44523e90450d53911e67f4]
  permission_script: mkdir reports && chmod +x ./scripts/database_make.py && chmod +x ./scripts/database_html.sh && chmod +x .cirrus/upload.sh
  sanity_script: ./scripts/database_make.py yosys-sanity ./verilog/ && ./scripts/database_html.sh && cp ./database/index.html ./reports/benchmarks_sanity.html
  push_script:  .cirrus/upload.sh
